data:
  # root: fine-tune-attack # self append
  # train_file: 'filelists/train.txt'
  # val_file: 'filelists/eval.txt'
  # train_file: 'fine-tune-attack/generator/data/train.txt'
  # val_file: 'fine-tune-attack/generator/data/eval.txt'
  root: fine-tune-attack/data # self append
#############################
train:
  num_workers: 0
  batch_size: 4
  optimizer: 'adam'
  seed: 1234
  adam:
    lr: 0.0002
    beta1: 0.8
    beta2: 0.99
  mel_lamb: 5
  stft_lamb: 2.5
  # lora: True
  lora: False
  pretrain: 'model_pretrain/maxgan_pretrain_16K_5L.pth'
  # epochs: 100
  # epochs: 10000
  epochs: 1000
#############################
audio:
  n_mel_channels: 100
  segment_length: 8000 # Should be multiple of 160
  pad_short: 2000
  filter_length: 512
  hop_length: 160 # WARNING: this can't be changed.
  win_length: 512
  sampling_rate: 16000
  mel_fmin: 0.0
  mel_fmax: 8000.0
#############################
gen:
  upsample_rates: [5,4,2,2,2]
  upsample_kernel_sizes: [15,12,4,4,4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
#############################
mpd:
  periods: [2,3,5,7,11]
  kernel_size: 5
  stride: 3
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
mrd:
  resolutions: "[(1024, 120, 600), (2048, 240, 1200), (512, 50, 240)]" # (filter_length, hop_length, win_length)
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
#############################
log:
  summary_interval: 10
  # summary_interval: 500
  # validation_interval: 10
  # save_interval: 10
  validation_interval: 20
  save_interval: 20
  num_audio: 5
  # chkpt_dir: 'chkpt-16k'
  # log_dir: 'logs-16k'
  # chkpt_dir: 'chkpt-lora-16k'
  # log_dir: 'logs-lora-16k'
  # chkpt_dir: 'chkpt-16k-adver'
  # log_dir: 'logs-16k-adver'
  chkpt_dir: 'fine-tune-attack/generator/chkpt'
  log_dir: 'fine-tune-attack/generator/log'
